FROM php:8.0-apache

# ติดตั้ง Extension ที่จำเป็น
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli

# เปิดใช้งาน rewrite module และตั้งค่า ServerName เพื่อลด Error AH00558
RUN a2enmod rewrite
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# ตั้งค่าสิทธิ์โฟลเดอร์ html ให้ Apache อ่านไฟล์ได้
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

RUN apt-get update && apt-get upgrade -y